### PR TITLE
Feature initialise repo

### PR DESCRIPTION
**Pull request by AbuTalha3**
**In this Pull Request We have;-**
- Created a repository and made collaboration.
- Created a feature branch and added required files.
         - HTML 
         - CSS
         - INDEX.JS
 - Created an Awesome Book list App with minimum use of CSS
 - It can add Books and can store them in local storage
 - It can remove books and updates the indices of remaining items in array.
Screenshot 2023-08-08 152540

https://github.com/mutesihope/Awesome-Books-List/assets/127955219/1ab03cd6-ece9-41e3-a809-02858255f185

### CODE REVIEW

**Review by TedLivist — APPROVED** [review]
Wait!

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @AbuTalha3 and @mutesihope,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### There are three members in this team, but only two contributed. Kindly ensure everyone on the team contributes code to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AbuTalha3** [comment]
Hi Sir, Good afternoon

Denis Obotte was added to the team late on Monday and he is not in contact,
we have tried to contact him and sent a collaboration invitation but in
vain.
regards

**Review by mukhammadrizooff — APPROVED** [review]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

 

## Highlights
- No linter errors ✔️ 
- Correct GitHub Flow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
